### PR TITLE
Revert some changes to user edit page and tweak UX.

### PR DESCRIPTION
**Pull request by homotechsual**
- Fix edit user page for new layout. Add redirect to login for user with bad auth cookie.
- Update package-lock.json (1 high sev sec fix. 1 mod.
- Move raw user info back to main page, fix redirect for users with bad / expired cookies or missing roles to login - if they bypass the 403.
- Fix minor styling issues.

### CODE REVIEW

**Comment by KelvinTegelaar** [comment]
conflict on edituser changes I made to fix license processing.

**Comment by homotechsual** [comment]
If I just accept your incoming changes and wipe out mine the syntax in the file is invalid.

**Comment by KelvinTegelaar** [comment]
I'll try to resolve :)

**Comment by KelvinTegelaar** [comment]
can't seem to resolve this without breaking the file somehow. Dev works fine though 🤷‍♂️

**Comment by homotechsual** [comment]
Lemme look at it tomorrow :-)

**Comment by homotechsual** [comment]
Please wait for checks to complete. This also implements auto-darkmode.

**Comment by homotechsual** [comment]
The style lint failure is a false-positive, the ordering is correct.

**Pull request merged**
