### PR TITLE
TenantID in Alerts

### PR DESCRIPTION
**Pull request by Yoshify**
This PR goes hand-in-hand with PR 431 in CIPP-API [here](https://github.com/KelvinTegelaar/CIPP-API/pull/431)

This adds a switch to the Notification settings to optionally include the Tenant ID in alerts:
image

I've also added the TenantID as a column in the logbook, with handling for null values, falling back on 'None'.

Feedback is appreciated :)

### CODE REVIEW

**Comment by KelvinTegelaar** [comment]
Now that's what I'm talking about. Hot stuff! thank you.

**Comment by KelvinTegelaar** [comment]
Oh one thing, you're trying to merge to main. Please redo this PR for the dev branch. :)

**Comment by Yoshify** [comment]
Ah no worries - apologies, didn't realise there was a public dev branch for PRs. Allow me to correct it.

**Comment by Yoshify** [comment]
Changing base branch to dev here results in no merge conflicts but gross history. Would you like me to redo the PR on a clean (and correct) branch?

**Comment by KelvinTegelaar** [comment]
> Changing base branch to dev here results in no merge conflicts but gross history. Would you like me to redo the PR on a clean (and correct) branch?

Yes please!

**Pull request closed without merging**
