### PR TITLE
Update OpenID API Permission Name

### PR DESCRIPTION
**Pull request by cameronbrister**
Update OpenID name and description to match what's listed in Azure API Permissions blade for consistency.

Screen Shot 2022-02-18 at 23 26 45

### CODE REVIEW

**Comment by homotechsual** [comment]
We don’t require ‘openid’ we require ‘profile’ from the same section.

**Comment by cameronbrister** [comment]
@homotechsual I see, that makes sense now. What caused my confusion was this: as I was adding permissions to my deployment, I was copying / pasting the fully qualified API / Permissions name as-is from the CIPP docs versus scrolling down the list in the Azure Request API Permissions blade. 

When I copied "OpenID" from the "OpenID permissions - profile" line, the only option I was presented with was "openid". The popover description of that item shows "_...allows the app to see basic user profile information._" so I assumed it was incomplete documentation.

For consistency, it'd be nice to change "OpenID permissions - profile" to "profile" but I think that's splitting hairs, and now I understand why it's listed the way that it is. Thanks for the clarification!

**Comment by homotechsual** [comment]
Please feel free to submit a PR changing it to profile

**Comment by homotechsual** [comment]
LGTM

**Pull request merged**
