### PR TITLE
Added Quad9 as a third DNS resolver option 

### PR DESCRIPTION
**Pull request by knightian**
Sorry about the pull spam I restructured the way I'm doing things so that each feature starts from a fresh dev base on its own branch and then merges in to your dev I think this will be cleaner than what I was doing.

### CODE REVIEW

**Comment by KelvinTegelaar** [comment]
your package.lock file contains incorrect params and the build fails, please fix this before I can pull in these changes.

**Comment by knightian** [comment]
> your package.lock file contains incorrect params and the build fails, please fix this before I can pull in these changes.

Didn't https://github.com/KelvinTegelaar/CIPP/pull/960/commits/2a7cd2e99fccf2bbc432130385fc66686e013380 fix that?

**Comment by knightian** [comment]
> your package.lock file contains incorrect params and the build fails, please fix this before I can pull in these changes.

Yea there is only 1 file changed with this pull and it's not package-lock.json @KelvinTegelaar

**Comment by knightian** [comment]
Screen Shot 2022-06-12 at 5 56 02 am

**Pull request merged**
